[package]
name = "randmst"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.6.1"
